# Generated by Django 5.2.8 on 2026-03-30 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0009_registration_campaign_owner_i18n"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrationfield",
            name="sort_order",
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name="Порядок"),
        ),
    ]
