# Generated by Django 5.2.8 on 2026-03-30 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0010_alter_registrationfield_sort_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registrationcampaign",
            name="ticket_heading_en",
        ),
        migrations.RemoveField(
            model_name="registrationcampaign",
            name="ticket_heading_ky",
        ),
        migrations.RemoveField(
            model_name="registrationcampaign",
            name="ticket_heading_ru",
        ),
        migrations.RemoveField(
            model_name="registrationcampaign",
            name="ticket_participant_label_en",
        ),
        migrations.RemoveField(
            model_name="registrationcampaign",
            name="ticket_participant_label_ky",
        ),
        migrations.RemoveField(
            model_name="registrationcampaign",
            name="ticket_participant_label_ru",
        ),
        migrations.AddField(
            model_name="registrationcampaign",
            name="ticket_pdf_field_keys",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="registrationcampaign",
            name="ticket_print_field_keys",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
