# Generated by Django 5.2.8 on 2026-03-30 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_remove_registrationcampaign_ticket_heading_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationcampaign',
            name='applicant_email_body',
            field=models.TextField(blank=True, help_text='Текст письма (plain text) и красивая HTML-версия с той же информацией и таблицей полей формируются автоматически. Подстановки: {ключ_поля}; {applicant_name}, {applicant_email}; {campaign_title}, {campaign_subtitle}, {campaign_slug}, {submission_id}; {campaign_event_dates}, {campaign_event_schedule}, {campaign_event_location}, {campaign_event_contact}; {ticket_url}, {ticket_pdf_url}, {ticket_code}; {all_fields}.', verbose_name='Текст письма заявителю (plain text)'),
        ),
        migrations.AlterField(
            model_name='registrationcampaign',
            name='applicant_email_body_en',
            field=models.TextField(blank=True, help_text='Текст письма (plain text) и красивая HTML-версия с той же информацией и таблицей полей формируются автоматически. Подстановки: {ключ_поля}; {applicant_name}, {applicant_email}; {campaign_title}, {campaign_subtitle}, {campaign_slug}, {submission_id}; {campaign_event_dates}, {campaign_event_schedule}, {campaign_event_location}, {campaign_event_contact}; {ticket_url}, {ticket_pdf_url}, {ticket_code}; {all_fields}.', null=True, verbose_name='Текст письма заявителю (plain text)'),
        ),
        migrations.AlterField(
            model_name='registrationcampaign',
            name='applicant_email_body_ky',
            field=models.TextField(blank=True, help_text='Текст письма (plain text) и красивая HTML-версия с той же информацией и таблицей полей формируются автоматически. Подстановки: {ключ_поля}; {applicant_name}, {applicant_email}; {campaign_title}, {campaign_subtitle}, {campaign_slug}, {submission_id}; {campaign_event_dates}, {campaign_event_schedule}, {campaign_event_location}, {campaign_event_contact}; {ticket_url}, {ticket_pdf_url}, {ticket_code}; {all_fields}.', null=True, verbose_name='Текст письма заявителю (plain text)'),
        ),
        migrations.AlterField(
            model_name='registrationcampaign',
            name='applicant_email_body_ru',
            field=models.TextField(blank=True, help_text='Текст письма (plain text) и красивая HTML-версия с той же информацией и таблицей полей формируются автоматически. Подстановки: {ключ_поля}; {applicant_name}, {applicant_email}; {campaign_title}, {campaign_subtitle}, {campaign_slug}, {submission_id}; {campaign_event_dates}, {campaign_event_schedule}, {campaign_event_location}, {campaign_event_contact}; {ticket_url}, {ticket_pdf_url}, {ticket_code}; {all_fields}.', null=True, verbose_name='Текст письма заявителю (plain text)'),
        ),
        migrations.AlterField(
            model_name='registrationcampaign',
            name='applicant_email_subject_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тема письма заявителю'),
        ),
        migrations.AlterField(
            model_name='registrationcampaign',
            name='applicant_email_subject_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тема письма заявителю'),
        ),
        migrations.AlterField(
            model_name='registrationcampaign',
            name='applicant_email_subject_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тема письма заявителю'),
        ),
        migrations.AlterField(
            model_name='registrationcampaign',
            name='event_contact_en',
            field=models.CharField(blank=True, help_text='Например: +996 775 000 005 · info@icee.kg', max_length=255, null=True, verbose_name='Контакты оргкомитета'),
        ),
        migrations.AlterField(
            model_name='registrationcampaign',
            name='event_contact_ky',
            field=models.CharField(blank=True, help_text='Например: +996 775 000 005 · info@icee.kg', max_length=255, null=True, verbose_name='Контакты оргкомитета'),
        ),
        migrations.AlterField(
            model_name='registrationcampaign',
            name='event_contact_ru',
            field=models.CharField(blank=True, help_text='Например: +996 775 000 005 · info@icee.kg', max_length=255, null=True, verbose_name='Контакты оргкомитета'),
        ),
        migrations.AlterField(
            model_name='registrationcampaign',
            name='event_dates_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Даты проведения'),
        ),
        migrations.AlterField(
            model_name='registrationcampaign',
            name='event_dates_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Даты проведения'),
        ),
        migrations.AlterField(
            model_name='registrationcampaign',
            name='event_dates_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Даты проведения'),
        ),
        migrations.AlterField(
            model_name='registrationcampaign',
            name='event_location_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Место проведения'),
        ),
        migrations.AlterField(
            model_name='registrationcampaign',
            name='event_location_ky',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Место проведения'),
        ),
        migrations.AlterField(
            model_name='registrationcampaign',
            name='event_location_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Место проведения'),
        ),
        migrations.AlterField(
            model_name='registrationcampaign',
            name='event_schedule_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Время работы'),
        ),
        migrations.AlterField(
            model_name='registrationcampaign',
            name='event_schedule_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Время работы'),
        ),
        migrations.AlterField(
            model_name='registrationcampaign',
            name='event_schedule_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Время работы'),
        ),
        migrations.AlterField(
            model_name='registrationcampaign',
            name='participation_terms_en',
            field=models.TextField(blank=True, help_text='Показываются под формой регистрации.', null=True, verbose_name='Условия участия'),
        ),
        migrations.AlterField(
            model_name='registrationcampaign',
            name='participation_terms_ky',
            field=models.TextField(blank=True, help_text='Показываются под формой регистрации.', null=True, verbose_name='Условия участия'),
        ),
        migrations.AlterField(
            model_name='registrationcampaign',
            name='participation_terms_ru',
            field=models.TextField(blank=True, help_text='Показываются под формой регистрации.', null=True, verbose_name='Условия участия'),
        ),
        migrations.AlterField(
            model_name='registrationcampaign',
            name='slug',
            field=models.SlugField(help_text='Латиница и цифры, например: ucastie-2026. Адрес формы: /r/этот-код/', max_length=80, unique=True, verbose_name='Код в URL'),
        ),
        migrations.AlterField(
            model_name='registrationcampaign',
            name='staff_email_body_en',
            field=models.TextField(blank=True, help_text='Если заполнено — уходит этот текст (с подстановками). Если пусто — автоматическая сводка полей и ссылка на билет. Те же плейсхолдеры, что и у письма заявителю: {all_fields}, {ticket_pdf_url}, поля формы {ключ}, и т.д.', null=True, verbose_name='Текст письма организаторам (plain text)'),
        ),
        migrations.AlterField(
            model_name='registrationcampaign',
            name='staff_email_body_ky',
            field=models.TextField(blank=True, help_text='Если заполнено — уходит этот текст (с подстановками). Если пусто — автоматическая сводка полей и ссылка на билет. Те же плейсхолдеры, что и у письма заявителю: {all_fields}, {ticket_pdf_url}, поля формы {ключ}, и т.д.', null=True, verbose_name='Текст письма организаторам (plain text)'),
        ),
        migrations.AlterField(
            model_name='registrationcampaign',
            name='staff_email_body_ru',
            field=models.TextField(blank=True, help_text='Если заполнено — уходит этот текст (с подстановками). Если пусто — автоматическая сводка полей и ссылка на билет. Те же плейсхолдеры, что и у письма заявителю: {all_fields}, {ticket_pdf_url}, поля формы {ключ}, и т.д.', null=True, verbose_name='Текст письма организаторам (plain text)'),
        ),
        migrations.AlterField(
            model_name='registrationcampaign',
            name='staff_email_subject_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тема письма организаторам'),
        ),
        migrations.AlterField(
            model_name='registrationcampaign',
            name='staff_email_subject_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тема письма организаторам'),
        ),
        migrations.AlterField(
            model_name='registrationcampaign',
            name='staff_email_subject_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тема письма организаторам'),
        ),
        migrations.AlterField(
            model_name='registrationcampaign',
            name='subtitle',
            field=models.CharField(blank=True, max_length=500, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='registrationcampaign',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='registrationcampaign',
            name='subtitle_ky',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='registrationcampaign',
            name='subtitle_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='registrationcampaign',
            name='success_message_en',
            field=models.TextField(blank=True, help_text='Если пусто — показывается стандартное сообщение.', null=True, verbose_name='Текст на странице «Спасибо»'),
        ),
        migrations.AlterField(
            model_name='registrationcampaign',
            name='success_message_ky',
            field=models.TextField(blank=True, help_text='Если пусто — показывается стандартное сообщение.', null=True, verbose_name='Текст на странице «Спасибо»'),
        ),
        migrations.AlterField(
            model_name='registrationcampaign',
            name='success_message_ru',
            field=models.TextField(blank=True, help_text='Если пусто — показывается стандартное сообщение.', null=True, verbose_name='Текст на странице «Спасибо»'),
        ),
        migrations.AlterField(
            model_name='registrationcampaign',
            name='ticket_footer_note_en',
            field=models.TextField(blank=True, help_text='Короткая памятка, которая выводится внизу страницы/билета.', null=True, verbose_name='Текст внизу билета'),
        ),
        migrations.AlterField(
            model_name='registrationcampaign',
            name='ticket_footer_note_ky',
            field=models.TextField(blank=True, help_text='Короткая памятка, которая выводится внизу страницы/билета.', null=True, verbose_name='Текст внизу билета'),
        ),
        migrations.AlterField(
            model_name='registrationcampaign',
            name='ticket_footer_note_ru',
            field=models.TextField(blank=True, help_text='Короткая памятка, которая выводится внизу страницы/билета.', null=True, verbose_name='Текст внизу билета'),
        ),
        migrations.AlterField(
            model_name='registrationcampaign',
            name='ticket_pdf_field_keys',
            field=models.CharField(blank=True, default='', help_text='Через запятую: например first_name,last_name,company.', max_length=500, verbose_name='Ключи полей для PDF-билета'),
        ),
        migrations.AlterField(
            model_name='registrationcampaign',
            name='ticket_print_field_keys',
            field=models.CharField(blank=True, default='', help_text='Через запятую: например first_name,last_name,company.', max_length=500, verbose_name='Ключи полей для печатного билета'),
        ),
        migrations.AlterField(
            model_name='registrationcampaign',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок формы'),
        ),
        migrations.AlterField(
            model_name='registrationcampaign',
            name='title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок формы'),
        ),
        migrations.AlterField(
            model_name='registrationcampaign',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок формы'),
        ),
        migrations.AlterField(
            model_name='registrationfield',
            name='choices_text_en',
            field=models.TextField(blank=True, help_text='Каждая строка: значение|Подпись, например: in_person|Очная', null=True, verbose_name='Варианты (для списка)'),
        ),
        migrations.AlterField(
            model_name='registrationfield',
            name='choices_text_ky',
            field=models.TextField(blank=True, help_text='Каждая строка: значение|Подпись, например: in_person|Очная', null=True, verbose_name='Варианты (для списка)'),
        ),
        migrations.AlterField(
            model_name='registrationfield',
            name='choices_text_ru',
            field=models.TextField(blank=True, help_text='Каждая строка: значение|Подпись, например: in_person|Очная', null=True, verbose_name='Варианты (для списка)'),
        ),
        migrations.AlterField(
            model_name='registrationfield',
            name='label_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Подпись'),
        ),
        migrations.AlterField(
            model_name='registrationfield',
            name='label_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Подпись'),
        ),
        migrations.AlterField(
            model_name='registrationfield',
            name='label_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Подпись'),
        ),
    ]
