# Generated by Django 5.2.8 on 2026-03-30 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_registrationcampaign_applicant_email_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationcampaign',
            name='ticket_print_heading',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Заголовок печатного билета'),
        ),
        migrations.AddField(
            model_name='registrationcampaign',
            name='ticket_subtitle',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Подзаголовок электронного билета'),
        ),
    ]
