# Generated by Codex on 2026-04-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0013_registrationcampaign_ticket_print_heading_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrationcampaign",
            name="sender_email",
            field=models.EmailField(
                blank=True,
                help_text="Если пусто, используется DEFAULT_FROM_EMAIL из настроек проекта.",
                max_length=254,
                verbose_name="Email отправителя",
            ),
        ),
    ]
