# Generated by Codex on 2026-04-15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0014_registrationcampaign_sender_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationEmailSender",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="Email отправителя")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Email отправителя",
                "verbose_name_plural": "Email отправителей",
                "ordering": ["title", "email"],
            },
        ),
        migrations.AddField(
            model_name="registrationcampaign",
            name="sender_address",
            field=models.ForeignKey(
                blank=True,
                help_text="Если не выбран, используется DEFAULT_FROM_EMAIL из настроек проекта.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="campaigns",
                to="account.registrationemailsender",
                verbose_name="Email отправителя",
            ),
        ),
    ]
