# Generated by Codex after moving ticket labels/help texts to the model.

from django.db import migrations, models


def copy_existing_ticket_texts_to_ru(apps, schema_editor):
    RegistrationCampaign = apps.get_model("account", "RegistrationCampaign")
    field_names = (
        "ticket_heading",
        "ticket_subtitle",
        "ticket_print_heading",
        "ticket_participant_label",
    )
    for campaign in RegistrationCampaign.objects.all().iterator():
        update_fields = []
        for field_name in field_names:
            ru_field_name = f"{field_name}_ru"
            value = getattr(campaign, field_name, "")
            if value and not getattr(campaign, ru_field_name, None):
                setattr(campaign, ru_field_name, value)
                update_fields.append(ru_field_name)
        if update_fields:
            campaign.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0016_delete_exhibitionvisitor"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrationcampaign",
            name="ticket_heading_ru",
            field=models.CharField(
                blank=True,
                help_text="Заголовок в верхней части билета (например: ЭЛЕКТРОННЫЙ БИЛЕТ / ПОДТВЕРЖДЕНИЕ).",
                max_length=255,
                null=True,
                verbose_name="Заголовок электронного билета",
            ),
        ),
        migrations.AddField(
            model_name="registrationcampaign",
            name="ticket_heading_en",
            field=models.CharField(
                blank=True,
                help_text="Заголовок в верхней части билета (например: ЭЛЕКТРОННЫЙ БИЛЕТ / ПОДТВЕРЖДЕНИЕ).",
                max_length=255,
                null=True,
                verbose_name="Заголовок электронного билета",
            ),
        ),
        migrations.AddField(
            model_name="registrationcampaign",
            name="ticket_heading_ky",
            field=models.CharField(
                blank=True,
                help_text="Заголовок в верхней части билета (например: ЭЛЕКТРОННЫЙ БИЛЕТ / ПОДТВЕРЖДЕНИЕ).",
                max_length=255,
                null=True,
                verbose_name="Заголовок электронного билета",
            ),
        ),
        migrations.AddField(
            model_name="registrationcampaign",
            name="ticket_subtitle_ru",
            field=models.CharField(
                blank=True,
                help_text="Текст под заголовком электронного билета.",
                max_length=255,
                null=True,
                verbose_name="Подзаголовок электронного билета",
            ),
        ),
        migrations.AddField(
            model_name="registrationcampaign",
            name="ticket_subtitle_en",
            field=models.CharField(
                blank=True,
                help_text="Текст под заголовком электронного билета.",
                max_length=255,
                null=True,
                verbose_name="Подзаголовок электронного билета",
            ),
        ),
        migrations.AddField(
            model_name="registrationcampaign",
            name="ticket_subtitle_ky",
            field=models.CharField(
                blank=True,
                help_text="Текст под заголовком электронного билета.",
                max_length=255,
                null=True,
                verbose_name="Подзаголовок электронного билета",
            ),
        ),
        migrations.AddField(
            model_name="registrationcampaign",
            name="ticket_print_heading_ru",
            field=models.CharField(
                blank=True,
                help_text="Отдельный заголовок для страницы печати.",
                max_length=255,
                null=True,
                verbose_name="Заголовок печатного билета",
            ),
        ),
        migrations.AddField(
            model_name="registrationcampaign",
            name="ticket_print_heading_en",
            field=models.CharField(
                blank=True,
                help_text="Отдельный заголовок для страницы печати.",
                max_length=255,
                null=True,
                verbose_name="Заголовок печатного билета",
            ),
        ),
        migrations.AddField(
            model_name="registrationcampaign",
            name="ticket_print_heading_ky",
            field=models.CharField(
                blank=True,
                help_text="Отдельный заголовок для страницы печати.",
                max_length=255,
                null=True,
                verbose_name="Заголовок печатного билета",
            ),
        ),
        migrations.AddField(
            model_name="registrationcampaign",
            name="ticket_participant_label_ru",
            field=models.CharField(
                blank=True,
                help_text="Общий текст перед именем участника (например: Участник).",
                max_length=255,
                null=True,
                verbose_name="Подпись перед ФИО участника",
            ),
        ),
        migrations.AddField(
            model_name="registrationcampaign",
            name="ticket_participant_label_en",
            field=models.CharField(
                blank=True,
                help_text="Общий текст перед именем участника (например: Участник).",
                max_length=255,
                null=True,
                verbose_name="Подпись перед ФИО участника",
            ),
        ),
        migrations.AddField(
            model_name="registrationcampaign",
            name="ticket_participant_label_ky",
            field=models.CharField(
                blank=True,
                help_text="Общий текст перед именем участника (например: Участник).",
                max_length=255,
                null=True,
                verbose_name="Подпись перед ФИО участника",
            ),
        ),
        migrations.RunPython(copy_existing_ticket_texts_to_ru, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="registrationcampaign",
            name="ticket_heading",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Заголовок в верхней части билета (например: ЭЛЕКТРОННЫЙ БИЛЕТ / ПОДТВЕРЖДЕНИЕ).",
                max_length=255,
                verbose_name="Заголовок электронного билета",
            ),
        ),
        migrations.AlterField(
            model_name="registrationcampaign",
            name="ticket_subtitle",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Текст под заголовком электронного билета.",
                max_length=255,
                verbose_name="Подзаголовок электронного билета",
            ),
        ),
        migrations.AlterField(
            model_name="registrationcampaign",
            name="ticket_print_heading",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Отдельный заголовок для страницы печати.",
                max_length=255,
                verbose_name="Заголовок печатного билета",
            ),
        ),
        migrations.AlterField(
            model_name="registrationcampaign",
            name="ticket_participant_label",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Общий текст перед именем участника (например: Участник).",
                max_length=255,
                verbose_name="Подпись перед ФИО участника",
            ),
        ),
        migrations.AlterField(
            model_name="registrationcampaign",
            name="ticket_footer_note",
            field=models.TextField(
                blank=True,
                help_text="Отображается на странице билета и в печатной версии с форматированием (как в редакторе).",
                verbose_name="Текст снизу",
            ),
        ),
        migrations.AlterField(
            model_name="registrationcampaign",
            name="ticket_footer_note_ru",
            field=models.TextField(
                blank=True,
                help_text="Отображается на странице билета и в печатной версии с форматированием (как в редакторе).",
                null=True,
                verbose_name="Текст снизу",
            ),
        ),
        migrations.AlterField(
            model_name="registrationcampaign",
            name="ticket_footer_note_en",
            field=models.TextField(
                blank=True,
                help_text="Отображается на странице билета и в печатной версии с форматированием (как в редакторе).",
                null=True,
                verbose_name="Текст снизу",
            ),
        ),
        migrations.AlterField(
            model_name="registrationcampaign",
            name="ticket_footer_note_ky",
            field=models.TextField(
                blank=True,
                help_text="Отображается на странице билета и в печатной версии с форматированием (как в редакторе).",
                null=True,
                verbose_name="Текст снизу",
            ),
        ),
        migrations.AlterField(
            model_name="registrationcampaign",
            name="ticket_pdf_field_keys",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Ключи полей формы через запятую, которые нужно показать в электронном билете и PDF.",
                max_length=500,
                verbose_name="Доп. поля электронного билета",
            ),
        ),
        migrations.AlterField(
            model_name="registrationcampaign",
            name="ticket_print_field_keys",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Ключи полей формы через запятую, которые нужно показать только в печати.",
                max_length=500,
                verbose_name="Доп. поля печатного билета",
            ),
        ),
    ]
